language: python

sudo: required
dist: trusty

python:
  - "3.5"
  - "3.4"

before_install:
  - sudo sed -i 's/us-central1.gce/us-central1.gce.clouds/' /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-lang-cjk oracle-java8-installer

install:
  - "pip install -r pip-requirements.txt"
  - "pip install coveralls"

before_script:
  - wget https://github.com/ajaxorg/ace-builds/archive/v1.2.3.tar.gz -O /tmp/ace.tar.gz
  - mkdir /tmp/ace-builds
  - tar -xvf /tmp/ace.tar.gz -C /tmp/ace-builds --strip-components 1
  - mkdir static/ace-builds
  - mv /tmp/ace-builds/src-noconflict static/ace-builds/
  - wget https://github.com/redpen-cc/redpen/releases/download/redpen-1.4.3/redpen-1.4.3.tar.gz -O /tmp/redpen.tar.gz
  - mkdir redpen
  - tar -xvf /tmp/redpen.tar.gz -C redpen --strip-components 1
  - export PATH=$PATH:$PWD/redpen/bin/

script: nosetests --with-coverage --cover-package=WebTeX.py

after_success: coveralls --rcfile=.coveragerc