language: python
python:
  - "3.5"
  - "3.4"
install:
  - "pip install -r pip-requirements.txt"
  - "pip install coveralls"
script: nosetests --with-coverage --cover-package=WebTeX.py
after_success: coveralls --rcfile=.coveragerc